### ISSUE TITLE
Why not upgrade to the python 3 support?

### ISSUE THREAD

**Issue by hongyi-zhao** [BerkeleyGW/BGWpy#7]
Hi,

The [requirements](https://github.com/BerkeleyGW/BGWpy#requirements) says:  python 2.7 required (Python 3 not supported at the moment).

But as we all know, python 2.x has reached its deadline and retried now. So why not upgrade to the python 3 support?

Regards,
HY

**Comment by GkAntonius** [comment]
It has been upgraded to python 3 since 2019, but we forgot to update the README file. Sorry for the confusion.

**Comment by hongyi-zhao** [comment]
Thanks a lot for the clarification.
