### ISSUE TITLE
Add Runtime Options to Set All User Configuration Variables

### ISSUE THREAD

**Issue by ghost** [BerkeleyGW/BGWpy#9]
Currently, BGWpy has a `config/user_configuration.py` file which must be created by the user during package installation to set values for certain runtime variables related to the user's local environment.  While some of the variables in this file can be overriden at runtime, e.g. `default_mpi`, others cannot be overridden through the public API, e.g. `use_hdf5`.

We have received requests to start distributing BGWpy through package managers (conda, pip); however, the requirement of a user-created `config/user_configuration.py` file means that BGWpy can not be installed in the automated fashion necessary for a package manager.

One way to circumvent this problem is to allow the user to override all variables set in `config/user_configuration.py` at runtime through the public API.  This would allow us to have a default configuration file that could be used during automated install, which the user could override at runtime to correspond to their local environment.

**Comment by GkAntonius** [comment]
A more standard way to set up the user configuration would be to place a configuration file in the user home (say `.BGWpyrc`) and read it through the [configparser](https://docs.python.org/3/library/configparser.html) library. I think that would make the module compatible with standard package managers.

As for setting up the options at runtime, it would be convenient, but right now I don't see how to do this without changing too much the user interface. Ideally it would work in the same way that matplotlib uses rcparam.

**Comment by ghost** [comment]
So you're thinking having all the configuration variables residing in a singleton object?  I could start messing around with package managers to see if that avenue would work, if you're interested.

**Comment by GkAntonius** [comment]
Yes. I started to play with that on my end, but I don't know when I'll find the time to make an implementation.

**Comment by GkAntonius** [comment]
So the module now makes use of a `~/.BGWpyrc` file, which can be generated with the script `BGWpy_make_config_file.py`. It is now possible to install BGWpy from pip!
